services:
  mysql:
    image: mysql:8.0
    container_name: bankapp-mysql
    environment:
        MYSQL_ROOT_PASSWORD: Test@123
        MYSQL_DATABASE: bankappdb
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - bankapp-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10


 # -----------------------------------------------------------
  # BANK APPLICATION SERVICE
  # -----------------------------------------------------------
  # By default this service builds the image using:
  #
  #    Dockerfile.multistage
  #
  # If you want Docker Compose to build the application using
  # the normal Dockerfile instead of Dockerfile.multistage,
  # follow these steps:
  #
  # 1️⃣ Open docker-compose.yml
  #
  # 2️⃣ Modify the build section of the bankapp service.
  #
  # CURRENT CONFIGURATION (uses multistage build):
  #
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.multistage
  #
  # CHANGE IT TO:
  #
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #
  # OR simply:
  #
  #    build: .
  #
  # because Docker automatically looks for a file named
  # "Dockerfile" in the build context.
  #
  # 3️⃣ After modifying the file, rebuild the containers:
  #
  #    docker compose down
  #    docker compose up --build
  #
  # Docker Compose will now build the bankapp image using
  # the standard Dockerfile instead of the multistage one.
  #
  # -----------------------------------------------------------


  bankapp:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: bankapp
    ports:
    - "8081:8080"
    networks:
    - bankapp-nw
    environment:
      MYSQL_HOST: bankapp-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      OLLAMA_URL: http://ollama:11434
      
    depends_on:
      mysql:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - bankapp-nw
    volumes:
      - ollama-data:/root/.ollama
  


networks:
  bankapp-nw:
    driver: bridge

volumes:
  mysql-data:
  ollama-data: