name: Dockerfile Lint

on:
  workflow_call:

jobs:
    hadolint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Run hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile.multistage
              