name: Code Linting and SAST

on:
  workflow_call:
    
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name : checkout code
              uses: actions/checkout@v4
              
            - name: Setup Java
              uses: actions/setup-java@v4 
              with:
                distribution: temurin
                java-version: 21

            - name: Make mvnw executable
              run: chmod +x mvnw    
                
            - name: Run Maven Checkstyle
              run: |
               ./mvnw checkstyle:check     
            
    sast:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run Semgrep SAST
              uses: returntocorp/semgrep-action@v1
              with:
                config: p/java  
           